python-lsp/python-lsp-ruff

pylsp_ruff/ruff_lint.py, tests/test_ruff_lint.py
=> Set ruff config to empty dict if pyproject.toml is present

README.md, pylsp_ruff/ruff_lint.py
It is preferable to disable the `mccabe` plugin in `pylsp` too, because `ruff` and therefore `pylsp-ruff` provides `mccabe`-like checking. Leaving the `mccabe` plugin enabled in `pylsp` may lead to confusing error messages.
=> Disable mccabe too since ruff provides this functionality

README.md, pylsp_ruff/ruff_lint.py
This PR disables pyflakes and replaces the issue/question in #8.
Since flake8 is disabled, pyflakes should probably be disabled too since it's enabled by python-lsp-server by default.
=> Disable pyflakes

.gitignore, pyproject.toml
This will make the plugin name and options namespace to match, which will allow to disable the plugin as expected.
Fixes #11
=> Change the entry point name to `ruff`

README.md, pylsp_ruff/ruff_lint.py, pyproject.toml, tests/test_ruff_lint.py
=> Feat extend select

README.md, pylsp_ruff/ruff_lint.py, pyproject.toml, tests/test_ruff_lint.py
Resolves #19.
Does the following:
- Add `extendIgnore` option
- Allow `extendIgnore` and `extendSelect` to be used if a `pyproject.toml` is present
=> extendIgnore and server settings

pylsp_ruff/plugin.py
It seems that applying code fixes in neovim is off by one column. For example, running sort imports on the following code:
```python
import json
import date
date
```
results in the following:
```python
iimport json
import date
ate
```
applying the this patch seems to solve the issue
=> Fixes off by one for code action fixes

pylsp_ruff/plugin.py
And not as `{"tool.ruff": {..}}`
This change will make sure that this boolean:
https://github.com/python-lsp/python-lsp-ruff/blob/f6707dfab9c39cbab23b8bc89646341164435afc/pylsp_ruff/plugin.py#L572-L573
will actually be set to `True` if a ruff config exists inside `pyproject.toml`
**Update**: I also added the config fixes commits of @martinal from #44 to this branch.
=> TOML dicts are formatted `{"tool" {"ruff": {..}}}`

README.md, pylsp_ruff/plugin.py
Removes flake8 from the list of `This plugin will disable [...] by default`. This doesn't change the existing behaviour at all:
The flake8 plugin is disabled by default in pylsp. If it's been enabled in the pylsp configuration then it's not actually possible for another plugin like this one to disable it.
The other four plugins disabled by python-lsp-ruff (pycodestyle, pyflakes, mccabe, pyls_isort) are enabled by default so the ruff plugin is able to disable these plugins, provided they're not explicitly enabled in the configuration.
Closes #46
Thanks for maintaining python-lsp-ruff, it's a very handy plugin! :grin:
=> settings: Don't try to disable flake8, document relevant limitation

pyproject.toml
This is part of the regression introduced with `ruff 0.1.0`. Users can install `python-lsp-ruff v.1.5.3` to work with `ruff<0.1.0`, otherwise the upcoming version `v.1.6.0` should be used.
=> Ruff minor v change fixup

README.md, pylsp_ruff/plugin.py, pylsp_ruff/ruff.py, pylsp_ruff/settings.py, pyproject.toml, tests/test_code_actions.py, tests/test_ruff_lint.py
This is a continuation of #48 since I want to capture all the new changes for the upcoming release in a version (and I didn't know renaming a branch closes a PR).
In particular, PR will
- enable support for ruff `0.1.0` and the new configuration option `unsafe-fixes`, and
- remove the now redundant call to `ruff` by lookup in the `PATH` and replace it with `sys.executable -m ruff` since this should be more reliable with different venv wrappers.
Closes #51. Closes #49.
=> Support new ruff version, fix wrong call to ruff through PATH

.github/workflows/python.yml
Based on https://github.com/python-lsp/python-lsp-ruff/pull/56#issuecomment-1800335566
=> Remove python v3.7 testing from CI

README.md, pylsp_ruff/plugin.py, tests/test_code_actions.py
Closes #55.
- Update unsafe code actions to contain `(unsafe)` at the end of the message
- Prevent the `Fix All` code action from applying unsafe codeactions
- Update the README to mention this behaviour
=> Update 'unsafe' code actions (#55)

README.md, pylsp_ruff/plugin.py, tests/test_code_actions.py, tests/test_ruff_format.py, tests/test_ruff_lint.py
Adds the Subcommand enum to indicate which `ruff` subcommand should be executed by `run_ruff`. At this time, only `check` and `format` are supported. As different subcommands support different parameters, argument generation is delegated based on the specific subcommand value.
The `ruff format` subcommand does not currently organize imports and there does not appear to be a way to convince it to do so. Until a unified command exists the approach taken here is to format and then make a second run of `ruff check` that _only_ performs import formatting.
Relates to #53.
=> Run `ruff format` when lsp formatting is invoked

README.md, pylsp_ruff/plugin.py, pylsp_ruff/settings.py
Added a setting for enabling/disabling [ruff Preview rules](https://docs.astral.sh/ruff/preview/)
This enables it for both `lint` and `format` actions, though `format` is not something this plugin supports for now. It doesn not seem that ruff supports different `--preview` flags for linting / formatting as of now.
Should likely be revisited if  https://github.com/python-lsp/python-lsp-ruff/issues/53 is being pursued :-)
=> [feat] Add setting for enabling/disabling Preview rules

pylsp_ruff/plugin.py
Adds the `preview` and the `targetVersion` settings to `ruff format`
=> Add target version and preview to formatter

README.md, pylsp_ruff/plugin.py, tests/test_ruff_lint.py
Allows to add loose severity codes to match all rules that start with the given pattern.
`D` would e.g. match **all** codes starting with `D`. If e.g. `D` and `D1` are given, any rule matching both would take the more precise one, so `D1` over `D`.
=> Add pattern matching to severities

pylsp_ruff/plugin.py
There are a couple of ways to fix #69.
* return an empty string after logging the error on line 520;
* fall back to running ruff via the python module (similar to previous behaviour, but with the option to not even attempt to run the executable if it's not specified).
This fix implements the second option as that will provide a better user experience. This assumes commit ea5f874a was simply intended to shortcut the attempt to call the executable if it was not set, rather than intended to remove the fallback behaviour.
Assigning to the `p` variable prior to opening pipes and checking for a `None` value felt like a better option than skipping the initial assignment and then trying to detect whether the variable has had a value assigned.
=> Fall back to python module if ruff executable is missing

README.md, pylsp_ruff/plugin.py, pyproject.toml
This fixes https://github.com/python-lsp/python-lsp-ruff/issues/79 - there are no deprecated/breaking changes that affects `python-lsp-ruff`, so we can safely bump to include `ruff` 0.2.x
And now that `ruff` has a formatter that is enabled by default, we should disable the default-enabled formatters, like `python-lsp-black` does: 
https://github.com/python-lsp/python-lsp-black/blob/307e87dbf74ff0227991d88cbc734113ce3fff68/pylsp_black/plugin.py#L60-L61
(I had an annoying issue with these and ruff fighting)
Ref: https://astral.sh/blog/ruff-v0.2.0 - https://github.com/astral-sh/ruff/releases/tag/v0.2.0
=> Allow ruff 0.2.x; disable default enabled formatters

.pre-commit-config.yaml, pyproject.toml
- Bump to version 2.1.0 with the new patch version in ruff
- Move to ruff for performing CI, remove black
- Use the new version of `lsprotocol` that avoid the `cattrs` bug in #61.
=> Bump to v2.1.0 in pyproject, update deps

pyproject.toml
Seems to work fine and unit tests all pass on the new ruff 0.3.0 release.
=> Relax ruff constraints to allow installing next to ruff 0.3.0

.gitignore, pylsp_ruff/plugin.py, pylsp_ruff/ruff.py, tests/test_code_actions.py
clear the 'fix all' meaning:
1, actually it is a 'term' which the 'all' meant all safe fixes only.
2, somehow some '(unsafe)' marker e.g F841 maybe would not be added, vs adding 'all safe fixes' suffix to 'fix all' probably would be a more direct meaning title.
=> Fix fixall title suffix

.pre-commit-config.yaml, pylsp_ruff/plugin.py
`E999` has been deprecated in ruff v0.5 and was replaced with `null` which translates to `"None"` in our package. Check instead if the code is `"None"`.
=> Update deprecated e999 check

pylsp_ruff/plugin.py
Like inbuilt plugins, ruff will also inform about linter and formatter working
it is actually useful because it inform user that pylsp is working properly and format is also working
=> notfy: give ack. about ruff linter and formatter

pylsp_ruff/plugin.py, tests/test_ruff_lint.py
otherwise I have to either configure the path in the project's pyproject.toml or unnecessarily in the lsp configuration :)
=> fall back to system ruff executable without executable setting

.gitignore, pylsp_ruff/plugin.py
=> Prevent showing cmd on Windows and add handling for ruff execution with `pythonw`

README.md, pylsp_ruff/plugin.py, pylsp_ruff/settings.py, tests/test_code_actions.py
=> Add unfixable config option
